#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.1 on Sun Feb 10 13:40:00 2019
#
# Codigo generado por wxGlade para probar y aprender la programacion de interfaz grafica
# con python usando la libreria wxPython

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana(wx.Frame): # Crea una clase llamada Ventana que hereda de la clase wx.Frame
    def __init__(self, *args, **kwds): # Crea la funcion encargada de inicializar la clase ventana
        # begin wxGlade: Ventana.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300)) # Ajusta el tamaño de la ventana que representa esta clase
        self.ExitButton = wx.Button(self, wx.ID_ANY, "Exit") # Crea un widget que en este caso es un boton pasando como parametros self, la id del boton y el texto que muestra
        self.changeColourButton = wx.Button(self, wx.ID_ANY, "Change colour")

        self.__set_properties() # Llama al metodo __set_properties para asignar o cambiar las propiedades que se quieran cambiar
        self.__do_layout() # Llama al metodo __do_layout para dibujar/crear el layout de la ventana

        self.Bind(wx.EVT_BUTTON, self.salir, self.ExitButton) # Enlaza el evento mediante el metodo bind() heredado de la clase wx.EvtHandler

        self.Bind(wx.EVT_BUTTON, self.onGridChange, self.changeColourButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Ventana.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Ventana.__do_layout
        grid_sizer_1 = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        ###
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        grid_sizer_1.Add(self.ExitButton, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        ###
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        grid_sizer_1.Add(self.changeColourButton, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        ###
        self.SetSizer(grid_sizer_1)
        self.Layout()
        # end wxGlade

    def salir(self, event):  # wxGlade: Ventana.<event_handler>
        self.Destroy() # Cierra la app
        event.Skip()

    def onGridChange(self, evt):
        row, col = 2, 1
        self.Sizer.SetCellBackgroundStyle(wx.BG_STYLE_COLOUR("GREEN"))
        self.Sizer.ForceRefresh()

# end of class Ventana

class MyApp(wx.App):
    def OnInit(self):
        self.frame = Ventana(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp
if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
